version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.11
    commands:
      - echo Installing Python dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Running export.py...
      - python export.py
artifacts:
  files:
    - '**/*'
  base-directory: '.'
