version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing system dependencies...
      - apt-get update
      - apt-get install -y graphviz
      - echo Installing Python dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Running export.py...
      - python export.py
artifacts:
  files:
    - 'build/*'  # Publish all files inside the build directory
  base-directory: 'build'
