{
    "meta": dict(priority=-30000, tableOfContentsSkip=True, skipFlare=True),
    "Children of Abraham, peace be upon you<br><br>": {},
    "There is one God, who has spoken to no one<br><br>": {},
    "The Book of Doctrine is the first book of the Third Testament": {},
    "It presents a philosophical framework that combines religious and scientific schools of thought": {},
    "It draws primarily upon Christian theology and contemporary cosmology": {},
    "The Book of Doctrine is a living document": {},
    "All precepts are open to comment, though doctrine is decided by the chief theologian": {},
    "The writings herein are so simple that a wise person can understand it by lunchtime, and a fool by sundown": {},
    "The Book of Doctrine standardizes the Deist religion": {},
    "It shall be referred to as Standard Doctrine, against which other worldly doctrines can be compared": {},
    "Standard Doctrine is compatible with the following theories": {
        "meta": {"type": "list"},
        "Big Bang theory": {},
        "Theory of Evolution": {},
        "Out-of-Africa Theory": {},
        "And Universe Creationism": {},
    },
}
