{
    "meta": dict(priority=-30000, tableOfContentsSkip=True),
    "There is one God, who has spoken to no one<br><br>": {},
    "The Book of Julian is the first book of the Third Testament": {},
    "It presents a philosophical framework that combines spiritual and scientific schools of thought": {},
    "It draws primarily upon Christian theology and contemporary cosmology": {},
    "Design principles of Book of Julian include:": {
        "meta": {"type": "list"},
        "Clarity": {
            "Hierarchical Organization": {},
            "Images": {},
            "Diagrams": {},
            "Metaphors": {},
            "Examples": {},
        },
        "Simplicity": {},
        "Brevity": {},
        "Accuracy": {},
        "Practical Value": {},
    },
    "When these principles are in conflict, simple expressions are preferred": {},
    "The writings herein are so simple that a wise person can understand it by lunchtime, and a fool by sundown": {},
    "The Book of Julian standardizes the Deist religion": {},
    "It shall be referred to as Standard Doctrine, against which other worldly doctrines can be compared": {},
    "Standard Doctrine is compatible with the following theories": {
        "meta": {"type": "list"},
        "Big Bang theory": {},
        "Theory of Evolution": {},
        "Out-of-Africa Theory": {},
        "Universe Creationism": {},
    },
}
