{
    "meta": {"priority": 0},
    "There is one God, who has spoken to no one<br><br>": {},
    "The Book of Julian is the first book of the Third Testament": {},
    "It presents a philosophical framework that combines spiritual and scientific schools of thought": {},
    "It draws primarily upon Christian theology and contemporary cosmology": {},
    "Design principles of Book of Julian include:": {
        "meta": {"type": "list"},
        "Clarity": {
            "Hierarchical Organization": {},
            "Images": {},
            "Diagrams": {},
            "Metaphors": {},
            "Examples": {},
        },
        "Simplicity": {},
        "Brevity": {},
        "Accuracy": {},
        "Practical Value": {},
    },
    "When these principles are in conflict, simple expressions are preferred": {},
    "The writings herein are so simple that a wise man can understand it by lunchtime, and a fool by sundown": {},
    "In the tradition of King James, we claim the following books as legacy. Consuming them will not harm you, but they are no longer canonical": {
        "First Testament": {
            "meta": {"type": "list"},
            "Genesis": {},
            "Exodus": {},
            "Leviticus": {},
            "Numbers": {},
            "Deuteronomy": {},
            "Joshua": {},
            "Judges": {},
            "Ruth": {},
            "1 Samuel": {},
            "2 Samuel": {},
            "1 Kings": {},
            "2 Kings": {},
            "1 Chronicles": {},
            "2 Chronicles": {},
            "Ezra": {},
            "Nehemiah": {},
            "Esther": {},
            "Job": {},
            "Psalms": {},
            "Proverbs": {},
            "Ecclesiastes": {},
            "Song of Solomon": {},
            "Isaiah": {},
            "Jeremiah": {},
            "Lamentations": {},
            "Ezekiel": {},
            "Daniel": {},
            "Hosea": {},
            "Joel": {},
            "Amos": {},
            "Obadiah": {},
            "Jonah": {},
            "Micah": {},
            "Nahum": {},
            "Habakkuk": {},
            "Zephaniah": {},
            "Haggai": {},
            "Zechariah": {},
            "Malachi": {},
        },
        "Second Testament": {
            "meta": {"type": "list"},
            "Matthew": {},
            "Mark": {},
            "Luke": {},
            "John": {},
            "The Acts": {},
            "Romans": {},
            "1 Corinthians": {},
            "2 Corinthians": {},
            "Galatians": {},
            "Ephesians": {},
            "Philippians": {},
            "Colossians": {},
            "1 Thessalonians": {},
            "2 Thessalonians": {},
            "1 Timothy": {},
            "2 Timothy": {},
            "Titus": {},
            "Philemon": {},
            "Hebrews": {},
            "James": {},
            "1 Peter": {},
            "2 Peter": {},
            "1 John": {},
            "2 John": {},
            "3 John": {},
            "Jude": {},
            "Revelation": {},
        },
    },
    "The following remain apocryphal": {
        "meta": {"type": "list"},
        "1 Esdras": {},
        "2 Esdras": {},
        "Tobit": {},
        "Judith": {},
        "Rest of Esther": {},
        "Wisdom": {},
        "Ecclesiasticus": {},
        "Baruch and the Epistle of Jeremy": {},
        "Song of the Three Children": {},
        "Story of Susanna": {},
        "The Idol Bel and the Dragon": {},
        "Prayer of Manasses": {},
        "1 Maccabees": {},
        "2 Maccabees": {},
    },
    "Finally, the canonical books of the Third Testament, which are the ultimate source of religious truth": {
        "meta": {"type": "list"},
        "Julian": {},
    },
}
