{
    "Introduction": {
        "The Deist Catechism is an accessible summary of Deist thought":{},
        "It serves children and adults, instructing them in what is right, and insulating them from what is wrong":{},
        "The Deist Catechism exists to edify the intellect, inspire ethical living, and cultivate a sense of awe and wonder towards the universe.":{}
    },
    "Catechism": {
        "What is the chief end of humankind?<br>": {"meta": dict(type="default")},
        "The chief end of humankind is to find God<br>": {},
        "Hasn't God been found already in the form of Yahweh, Jesus, and Allah?<br>": {"meta": dict(type="default")},
        "No, as these are false Gods": {},
        "No one has ever heard, nor seen them<br>": {},
        "Where is God?<br>":{},
        "God is outside of this universe<br>":{},
        "Can you see God?<br>":{},
        "Not at this time<br>":{},
        "Does God hear our prayers?<br>":{},
        "No. God does not hear us<br>":{},
        "Should you glorify God?<br>":{},
        "Sure, if you would like<br>":{},
        "Who were our first parents?<br>":{},
        "Chromosomal Adam and Eve, from Africa<br>":{},
        "Of what were our first parents made?<br>":{},
        "They were the continuation of an earlier, similar species<br>":{},
        "What is a covenant?<br>":{},
        "An agreement between two or more persons.<br>":{},
        "How many Gods are there?<br>":{},
        "One. The Creator God<br>":{},
        "Does God know all things?<br>":{},
        "No<br>":{},
        "Who wrote the Bible?<br>":{},
        "Ordinary people<br>":{},
        "Should I live my life according to the first two testaments?<br>":{},
        "No, as they are legacy. A better life doctrine is the Third Testament, which has superseded the first two<br>":{},
        "What is the purpose of religion?<br>": {"meta": dict(type="default")},
        "The purpose of religion is to empower the people socially<br>": {},
        "Am I not then equally served by attending a traditional house of worship?<br>": {"meta": dict(type="default")},
        "If you appreciate traditional doctrine, this is the better path for you<br>": {},
        "What is the Beatific Vision?<br>": {"meta": dict(type="default")},
        "The Beatific Vision will occur when humankind unequivocally witnesses the face of God<br>": {},
        "How will we know this event has occurred?<br>": {"meta": dict(type="default")},
        "You will investigate the claims scientifically<br>": {},
        "What is the Ascension?<br>": {"meta": dict(type="default")},
        "The Ascension is the period after the Beatific Vision in which we become communicant with God<br>": {},
    },
}
