{
    "meta": {"priority": 10000},
    "With respect to the major religious texts, we use the following abbreviations:":{
        "meta": {"type": "list"},
        "Torah : T":{},
        "Bible : B":{},
        "Koran : Q":{},
        "Julian : J":{},
    },
    "In the tradition of King James, we claim the following books as legacy. Consuming them will not harm you, but they are no longer canonical": {
        "First Testament": {
            "meta": {"type": "list"},
            "Torah":{   
                "Genesis": {},
                "Exodus": {},
                "Leviticus": {},
                "Numbers": {},
                "Deuteronomy": {},
            },
            "Historical":{
                "Joshua": {},
                "Judges": {},
                "Ruth": {},
                "1 Samuel": {},
                "2 Samuel": {},
                "1 Kings": {},
                "2 Kings": {},
                "1 Chronicles": {},
                "2 Chronicles": {},
                "Ezra": {},
                "Nehemiah": {},
                "Esther": {},
            },
            "Wisdom":{
                "Job": {},
                "Psalms": {},
                "Proverbs": {},
                "Ecclesiastes": {},
                "Song of Solomon": {},
            },
            "Major Prophets":{
                "Isaiah": {},
                "Jeremiah": {},
                "Lamentations": {},
                "Ezekiel": {},
                "Daniel": {},
            },
            "Minor Prophets":{
                "Hosea": {},
                "Joel": {},
                "Amos": {},
                "Obadiah": {},
                "Jonah": {},
                "Micah": {},
                "Nahum": {},
                "Habakkuk": {},
                "Zephaniah": {},
                "Haggai": {},
                "Zechariah": {},
                "Malachi": {},
            },
        },
        "Second Testament": {
            "meta": {"type": "list"},
            "The Gospels":{
                "Matthew": {},
                "Mark": {},
                "Luke": {},
                "John": {},
            },
            "Acts":{
                "The Acts": {},
            },
            "Pauline Epistles":{
                "Romans": {},
                "1 Corinthians": {},
                "2 Corinthians": {},
                "Galatians": {},
                "Ephesians": {},
                "Philippians": {},
                "Colossians": {},
                "1 Thessalonians": {},
                "2 Thessalonians": {},
                "1 Timothy": {},
                "2 Timothy": {},
                "Titus": {},
                "Philemon": {},
            },
            "General Epistles":{
                "Hebrews": {},
                "James": {},
                "1 Peter": {},
                "2 Peter": {},
                "1 John": {},
                "2 John": {},
                "3 John": {},
                "Jude": {},
            },
            "Apocalypse":{
                "Revelation": {},
            }
        },
    },
    "The following remain apocryphal": {
        "meta": {"type": "list"},
        "1 Esdras": {},
        "2 Esdras": {},
        "Tobit": {},
        "Judith": {},
        "Rest of Esther": {},
        "Wisdom": {},
        "Ecclesiasticus": {},
        "Baruch and the Epistle of Jeremy": {},
        "Song of the Three Children": {},
        "Story of Susanna": {},
        "The Idol Bel and the Dragon": {},
        "Prayer of Manasses": {},
        "1 Maccabees": {},
        "2 Maccabees": {},
    },
    "Finally, the canonical books of the Third Testament, which are the ultimate source of religious truth": {
        "meta": {"type": "list"},
        "Julian": {},
    },
}
