echo Installing system dependencies...
apt-get update
apt-get install -y graphviz
echo Installing Python dependencies...
pip install -r requirements.txt

echo Build started on `date`
echo Running export.py...
python export.py
